* Scripts for processing ICP-MS data

This project contains scripts for processing data produced by the
inductively coupled plasma mass spectrometry (ICP-MS).  It's possible
that these scripts could also be useful for processing other types of
depth/time series data, but that is at the discretion of the user.

** Requirements

   This project requires that [[https://www.python.org/download/releases/2.7/][Python 2.7]] is installed.  You can check
   if you already have python installed by typing the following.

#+BEGIN_SRC sh
python --version 2>&1
#+END_SRC

#+RESULTS:
: Python 2.7.13


** Contributors

   The following people have contributed to the scripts in this
   project.  If you have scientific questions, please ask the
   following people.

   - [[mailto:nicole.spaulding@maine.edu][Nicole Spaulding]]
   - [[mailto:heather.clifford@maine.edu][Heather Clifford]]

   For coding questions, please refer to the following people.

   - [[mailto:mark.royer@maine.edu][Mark Royer]]

#  LocalWords:  spectrometry
